### ISSUE TITLE
Parse Error on `rescue` within block

### ISSUE THREAD

**Issue by chrisdurheim** [presidentbeef/brakeman#1298] opened 2019-01-03 15:02 UTC
### Background

Brakeman version: 4.3.1
Rails version: 5.2.2
Ruby version: 2.5.1

Link to Rails application code: (see simple example below)

#### Parse Error

```
parse error on value ["rescue", 6] (kRESCUE)
Location: Could not parse {project}/app/controllers/test_controller.rb
```

Minimal example that does not parse:

```ruby
class TestController < ApplicationController
  def index
    array_of_stuff.each do |element|
      do_an_error_prone_thing_with(element)
    rescue ActiveRecord::RecordNotFound
      next
    end
  end
end
```

Ruby 2.5.0 supports `rescue` directly within `do` blocks, without an explicit call to `begin`. The above code, however, fails with a parsing error. I've checked this with `ruby_parse` and no errors were thrown.

Updating the code to explicitly define a `begin` and `end` with the rescue resolves the error in brakeman:

```ruby
class TestController < ApplicationController
  def index
    array_of_stuff.each do |element|
      begin
        do_an_error_prone_thing_with(element)
      rescue ActiveRecord::RecordNotFound
        next
      end
    end
  end
end
```

**Comment by presidentbeef** [comment] 2019-01-03 22:41
Hi @chrisdurheim,

This is a duplicate of #1173.

Thanks!

**Closed by presidentbeef** 2019-01-03 22:41 UTC
