### ISSUE TITLE
Failed to allocate memory error

### ISSUE THREAD

**Issue by cmendla-cct** [presidentbeef/brakeman#859] opened 2016-04-08 12:21 UTC
I installed Brakeman on a relatively small application. When I ran it locally on my development laptop (win 8) memory usage increased until I got a "Failed to allocate memory" error. 

I published the app to our development server running IIS. Memory usage kept increasing and I got the same error. 

```
C:\inetpub\wwwroot\development\internal_complaints>brakeman
Loading scanner...
Processing application in C:/inetpub/wwwroot/development/internal_complaints
Processing gems...
[Notice] Detected Rails 4 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
Processing initializers...
Processing libs...ssed
Processing routes...
Processing templates...
Processing data flow in templates...
Processing models...
[FATAL] failed to allocate memory
```

i tried running on my local machine with the -- skip libs option but that crashed also. 

Information for my development machine

   ruby 2.0.0p647 (2015-08-18) [i386-mingw32] 
   Rails 4.2.5

**Comment by cmendla-cct** [comment] 2016-04-08 12:33
Update - I ran Brakeman on my local machine with >> brakeman -n --faster and did get a report. 

Rails version: 4.2.5
Brakeman version: 3.2.1
Started at 2016-04-08 08:27:02 -0400
Duration: 2.025203 seconds

**Comment by presidentbeef** [comment] 2016-04-08 16:30
If you run with `-d` it should provide a hint as to which file/model is causing the issue. I don't suppose this is an open source application?

**Comment by cmendla-cct** [comment] 2016-04-08 16:50
Here is the tail end of the run with -d.

As far as the application - it is an internal rails app but I do use a number of gems.  I've attached the gemfile in case that would be useful. 

By the way, I tried running Brakeman on a similar app and it ran just fine without needing any parameters. 
[Gemfile.txt](https://github.com/presidentbeef/brakeman/files/210544/Gemfile.txt)



```

Processing C:/Users/cmendla/RubymineProjects/internal_complaints/app/models/defe
ct.rb
Processing C:/Users/cmendla/RubymineProjects/internal_complaints/app/models/docu
ment_history.rb
Processing C:/Users/cmendla/RubymineProjects/internal_complaints/app/models/fail
ed_login.rb
Processing C:/Users/cmendla/RubymineProjects/internal_complaints/app/models/page
.rb
Processing C:/Users/cmendla/RubymineProjects/internal_complaints/app/models/sear
ch.rb
[FATAL] failed to allocate memory

C:\Users\cmendla\RubymineProjects\internal_complaints>
```

Also, here is my memory right before the crash and right after. (the after comes first for some reason)

![temp memory 2](https://cloud.githubusercontent.com/assets/14942931/14391025/c75e0f72-fd87-11e5-8269-50c80e38b12c.jpg)
![temp memory](https://cloud.githubusercontent.com/assets/14942931/14391026/c75eab62-fd87-11e5-9fb5-c1e6d4d55438.jpg)

**Comment by presidentbeef** [comment] 2016-04-08 17:17
Unfortunately, without seeing the code there is not much I can do. Usually issues like this are caused by a lot of conditional expressions assigning to the same variable.

You can try adjusting the `--branch-limit` (default is 5, so try lower values) or run with `--no-branching`.

To make things easier, you can add a `brakeman.yml` file with the settings you need. The file can be generated like this:

`brakeman -C --branch-limit 2 > config/brakeman.yml`

**Comment by presidentbeef** [comment] 2016-07-04 02:02
Closing per above.

**Closed by presidentbeef** 2016-07-04 02:02 UTC
