### ISSUE TITLE
3.3.0 requires `coffee-rails` and `less-rails` gems

### ISSUE THREAD

**Issue by stephencattaneo** [presidentbeef/brakeman#877] opened 2016-05-11 18:16 UTC
Hi just upgraded to 3.3.0.

Now sprockets is fail for a missing "coffee_script" and "less" dependencies. As a work-around I had to add `coffee-rails` and `less-rails` to my Gemfile.  These two dependencies need to be added to brakeman's dependency list.

**Comment by presidentbeef** [comment] 2016-05-11 19:03
Hi Stephen,

Can you clarify the issue you are seeing? Brakeman has never depended on CoffeeScript or Less. Your application's dependencies should be explicitly declared and not rely on transitive dependencies from Brakeman.

**Comment by smangelsdorf** [comment] 2016-06-01 03:17
I am seeing this issue too.

```
$ rake db:migrate --trace
rake aborted!
LoadError: cannot load such file -- coffee_script
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/tilt-2.0.2/lib/tilt/coffee.rb:2:in `require'
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/tilt-2.0.2/lib/tilt/coffee.rb:2:in `<top (required)>'
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-2.12.4/lib/sprockets.rb:93:in `require'
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-2.12.4/lib/sprockets.rb:93:in `<module:Sprockets>'
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-2.12.4/lib/sprockets.rb:3:in `<top (required)>'
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/railtie.rb:5:in `require'
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/railtie.rb:5:in `<top (required)>'
/Users/shaun/Projects/my-rails-app/config/application.rb:9:in `require'
```

To me, it looks like a gem packaging issue:

https://gist.github.com/smangelsdorf/03806b1137e6e7e494ae2ff5129c925f

This seems to be deliberate (85c767b6) but has the side effect of messing with the versions mentioned in an app's `Gemfile`.

Modifying the installed gem to remove the `bundle` subdirectory resolves the issue for me, though for now I'll need to pin my Brakeman version to 3.2.x.

**Comment by presidentbeef** [comment] 2016-06-01 04:05
@smangelsdorf can you share your `Gemfile` or a minimal one that demonstrates the issue?

Also, you can always use the `brakeman-min` gem and resolve dependencies manually instead of downgrading.

**Comment by smangelsdorf** [comment] 2016-06-01 05:25
_(Sorry, this reply evolved as I worked through the problem, and ended up a little longer and more exploratory than I intended.)_

I've been able to reproduce it using this `Gemfile`:

```ruby
source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'sqlite3', '1.3.11'

group :development, :test do
  gem 'brakeman', '3.3.0'
end
```

And this `Rakefile`:

```ruby
require 'brakeman'

require File.expand_path('../config/application', __FILE__)
Rails.application.load_tasks

task :brakeman do
  Brakeman.run app_path: '.', print_report: true, exit_on_warn: true
end
```

Moving the `require 'brakeman'` call below the line which loads the Rails application works around the specific exception triggered here, and I'm willing to accept that it should be in that order anyway. However, on digging further I note the following which is independent of the `Rakefile`:

```
$ rails runner 'puts $LOAD_PATH.grep(/brakeman.+bundle/).join("\n")'
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/safe_yaml-1.0.4/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/erubis-2.7.0/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/sass-3.4.22/vendor/listen/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/sass-3.4.22/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/tilt-2.0.2/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/terminal-table-1.5.2/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/slim-3.0.6/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/temple-0.7.6/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/sexp_processor-4.7.0/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/ruby2ruby-2.3.0/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/ruby_parser-3.8.1/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/highline-1.7.8/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/haml-4.0.7/lib
```

So, the dependencies of brakeman are being injected into the `$LOAD_PATH` of the Rails application. This can, of course, be avoided by changing `Gemfile` to read:

```ruby
gem 'brakeman', '3.3.0', require: false
```

That said, in any case where the `brakeman` gem is loaded with a `require`, the resulting `$LOAD_PATH` causes one of two situations as far as I can see (apologies if I've misunderstood here):

* Brakeman's dependencies will be used instead of the dependencies of the Rails application (resulting in a runtime bundle inconsistent with `Gemfile.lock`)
* The Rails application's dependencies will be used instead of Brakeman's vendored versions (violating the version expectations of Brakeman)

Switching to `brakeman-min` appears at a glance to have its own set of problems – not the least of which is that `guard-brakeman` specifically requires `brakeman`, so the project ends up with both gems and ambiguous `require` behaviour:

```
$ rails runner 'puts $LOAD_PATH.grep(/brakeman/).join("\n")'
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/guard-brakeman-0.8.3/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-min-3.3.0/lib
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/lib
```

**Comment by presidentbeef** [comment] 2016-06-01 05:26
I cannot reproduce this issue. Probably using `gem 'brakeman', require: false` will fix it.

However, this reminds me that I have a branch where Brakeman only modifies the load path when it actually loads dependencies, essentially emulating `require: false`.

**Comment by presidentbeef** [comment] 2016-06-01 05:47
Funny how we probably both spent the last hour or so working on this and then posted at the same time. I still can't get the loading failures you are seeing, though.

`require: false` is *strongly* suggested. There's no reason to mix Brakeman's dependencies with your application's, and there is no reason to load your application to run Brakeman. This is why running Brakeman via a Rake task is no longer recommended.

The third dependency case you do not have in your list is: rely on Bundler to successfully match your application's dependencies and Brakeman's dependencies, even when it really doesn't matter. See #842, #767, #709, #659, #601, ##473, ##247, etc. Brakeman supports scanning all versions of Rails from 2.3.x to 4.x (with beta support for 5.beta). There is no way it can remain compatible with all the dependencies of all Rails apps.

Really, there is no winning solution if Brakeman is in your Gemfile and loaded with your application. It is not meant to be. It is essentially a standalone application.

**Comment by presidentbeef** [comment] 2016-06-01 05:48
Meant to add: I am thinking of also having a `brakeman-lib` gem which is essentially just like `brakeman` but without vendored dependencies.

**Comment by smangelsdorf** [comment] 2016-06-01 06:05
This all makes sense, thanks for looking into it.

> This is why running Brakeman via a Rake task is no longer recommended.

This is where I was coming unstuck. I'll need to stop doing that.

**Comment by smangelsdorf** [comment] 2016-06-01 06:12
Just for completeness I've distilled it a little more. The failure I saw with the `Gemfile` and `Rakefile` I included above were observable when running `bundle exec rake brakeman`. The specific issue was caused by loading `brakeman` before the bundle:

```
$ ruby -rbrakeman -rbundler/setup -e "require './config/environment'"
/Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/tilt-2.0.2/lib/tilt/coffee.rb:2:in `require': cannot load such file -- coffee_script (LoadError)
	from /Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/brakeman-3.3.0/bundle/ruby/2.3.0/gems/tilt-2.0.2/lib/tilt/coffee.rb:2:in `<top (required)>'
	from /Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-2.12.4/lib/sprockets.rb:93:in `require'
	from /Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-2.12.4/lib/sprockets.rb:93:in `<module:Sprockets>'
	from /Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-2.12.4/lib/sprockets.rb:3:in `<top (required)>'
	from /Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/railtie.rb:5:in `require'
	from /Users/shaun/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/railtie.rb:5:in `<top (required)>'
	from /Users/shaun/Projects/my-broken-app/config/application.rb:11:in `require'
	from /Users/shaun/Projects/my-broken-app/config/application.rb:11:in `<top (required)>'
	from /Users/shaun/Projects/my-broken-app/config/environment.rb:2:in `require'
	from /Users/shaun/Projects/my-broken-app/config/environment.rb:2:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
$ ruby -rbundler/setup -rbrakeman -e "require './config/environment'"
$
```

This changes nothing, of course. As noted, it's a load-order issue and the solution is to **never** load brakeman in the app's environment.

**Comment by presidentbeef** [comment] 2016-06-01 15:44
I *still* can't reproduce this, but I believe you.

It may be possible to somehow scope the load paths so they are separated out...but the code would still be loaded to the global namespace and could cause even more subtle issues.

**Comment by presidentbeef** [comment] 2016-07-04 02:01
Closing this one out. [3.3.1](http://brakemanscanner.org/blog/2016/06/03/brakeman-3-dot-3-1-released/) delays loading and [brakeman-lib](https://rubygems.org/gems/brakeman-lib) is available for a non-bundled package.

**Closed by presidentbeef** 2016-07-04 02:01 UTC
