### ISSUE TITLE
Parse error on symbol array shorthand

### ISSUE THREAD

**Issue by baburdick** [presidentbeef/brakeman#632] opened 2015-03-05 23:50 UTC
This code is a valid way to express an array of symbols (`%i{ foo bar }`. But the master branch of brakeman records a parsing error: `parse error on value "%i{" (error)`.

**Comment by presidentbeef** [comment] 2015-03-06 00:01
Hi Bruce,

Sorry, but I can't reproduce this issue. Can you provide a more complete code sample? What version of ruby_parser is installed?

**Comment by baburdick** [comment] 2015-03-06 01:31
ruby_parser v3.6.4 is installed. It may be that the array of symbols appears over multiple lines. If that's not it, I'm out of suggestions.
```ruby
  MULTILINE_ARRAY_OF_SYMBOLS = %i{ foo bar baz
                                   bilbo nimoy }.freeze
```

**Comment by presidentbeef** [comment] 2015-03-06 04:00
Hm, I still can't reproduce.

```
1.9.3-p484 :001 > require 'ruby_parser'
 => true
1.9.3-p484 :002 > RubyParser.new.parse "MULTILINE_ARRAY_OF_SYMBOLS = %i{ foo bar baz
1.9.3-p484 :003">                                   bilbo nimoy }.freeze"
 => s(:cdecl, :MULTILINE_ARRAY_OF_SYMBOLS, s(:call, s(:array, s(:lit, :foo), s(:lit, :bar), s(:lit, :baz), s(:lit, :bilbo), s(:lit, :nimoy)), :freeze))
```

**Comment by presidentbeef** [comment] 2015-05-13 19:02
Closing since I never reproduced the issue...and it's a ruby_parser issue anyway.

**Closed by presidentbeef** 2015-05-13 19:02 UTC
