### ISSUE TITLE
HEREDOC parse error & warning on SQL string with no substitution

### ISSUE THREAD

**Issue by RichardGrossman** [presidentbeef/brakeman#1025] opened 2017-03-28 20:13 UTC
: parse error on value "<<" (tLSHFT)          | Could not parse /Users/[etc]

Furthermore, this SQL string has no substitutions.
 def specialquery
    query =<<~SQL.gsub(/[\s\t]*\n/, ' ').strip
    select
    i.*,
    pi.*,
    p.*,
    p.id as "product_id"

    from product_ingredients pi
    join ingredients i on pi.ingredient_id = i.id
    join products p on pi.product_id = p.id
    order by
    p.description,
    pi.product_id,
    i.name
    SQL
    
    @report = Ingredient.find_by_sql(query)

**Comment by presidentbeef** [comment] 2017-03-28 22:40
Hi Richard,

The `<<~` syntax is not supported yet: https://github.com/seattlerb/ruby_parser/issues/218

If there is a parsing error on the `<<~` heredoc, then Brakeman can't be warning about it, and I was not able to reproduce a warning using the `<<-` syntax.

Please provide the warning message.

**Comment by presidentbeef** [comment] 2017-04-27 14:01
Going to close this. Please re-open if you can provide more information.

**Closed by presidentbeef** 2017-04-27 14:01 UTC
