### ISSUE TITLE
Failure parsing Ruby 2.7 beginless range

### ISSUE THREAD

**Issue by jbhannah** [presidentbeef/brakeman#1483] opened 2020-06-02 23:16 UTC
### Background

Brakeman version: 4.8.2
Rails version: 6.0.3.1
Ruby version: 2.7.1p83

#### Parse Error

(Consult https://brakemanscanner.org/docs/troubleshooting/parse_errors/ first. Note that (most) parsing errors are from the ruby_parser library, not Brakeman itself.)

Minimal example that does not parse:

```ruby
..1
...1
```

**Comment by presidentbeef** [comment] 2020-06-03 03:03
Hi @jbhannah,

Yes, `ruby_parser` does not support new 2.7 syntax.

**Comment by jbhannah** [comment] 2020-06-08 01:17
I found a workaround for my specific use case, but leaving this open until it's fixed upstream or @presidentbeef decides to close it, in case anyone else comes across this issue.

(Incidentally, my use case was an `expired` scope on a Rails model, mirroring an `active` scope. My initial approach using `...Time.zone.now` for `expired` is how I found this issue with `ruby_parser`, but the workaround was to [use some Arel magic to invert the `active` scope](https://jbhannah.net/articles/negating-activerecord-scopes).)

**Comment by tejasbubane** [comment] 2020-08-17 15:27
> Yes, `ruby_parser` does not support new 2.7 syntax yet.

Ruby parser supports 2.7 syntax and beginless range [since v2.6.3](https://github.com/whitequark/parser/blob/master/CHANGELOG.md#v2630-2019-04-28)

**Comment by presidentbeef** [comment] 2020-08-17 20:12
Thanks @tejasbubane but that is `parser` not https://github.com/seattlerb/ruby_parser. Similar names, similar functionality, but totally different :smile:

**Comment by tejasbubane** [comment] 2020-08-18 05:11
> Thanks @tejasbubane but that is parser not https://github.com/seattlerb/ruby_parser. Similar names, similar functionality, but totally different 😄

Ah, my bad.

**Comment by ybiquitous** [comment] 2020-10-05 07:16
I found a related issue, so I share it:
https://github.com/seattlerb/ruby_parser/issues/309

**Comment by jsugarman** [comment] 2021-02-22 20:59
Is this likely to be fixed in the near future? 

Having this issue with a rails helper for which brakeman throws `parse error on value "..." (tDOT3)`. Have worked around the issue using `--no-exit-on-error` switch for now (could also use `--skip-file`) but would prefer not to.

**Comment by ivan-denysov** [comment] 2021-04-16 12:31
Hi, @presidentbeef 
- Would it help `brakeman` to stay up to date with latest syntax if `brakeman` used [`parser`](https://github.com/whitequark/parser) instead of [`ruby_parser`](https://github.com/seattlerb/ruby_parser)? 
- Do you think this will be a complicated change? 
- Are there any downsides?

**Comment by presidentbeef** [comment] 2021-04-16 17:34
@ivan-denysov that would be a very significant change. Brakeman is very much tied to RubyParser's AST representation.

**Comment by presidentbeef** [comment] 2021-04-16 17:36
That being said, support for beginless ranges is already in RubyParser HEAD and so I plan to package that with the next Brakeman release. Planned for next week.

**Comment by presidentbeef** [comment] 2021-04-28 17:38
Added in `brakeman` 5.0.1 gem.

**Closed by presidentbeef** 2021-04-28 17:38 UTC

**Comment by presidentbeef** [comment] 2021-05-20 17:06
Hi @henryaj - are you using the [`brakeman`](https://rubygems.org/gems/brakeman) gem?

Can you provide a code sample? I can't reproduce this error otherwise.

**Comment by henryaj** [comment] 2021-05-21 15:18
Sure, here's the code it's tripping up on:

```
class ReapGeneratedPdfsWorker
  include Sidekiq::Worker

  def perform
    PdfGenerationJob.where(updated_at: ..15.minutes.ago).destroy_all
  end
end
```

I've got `brakeman` 5.0.1 specified in my Gemfile and am running `bundle exec brakeman` from the CLI.

**Comment by presidentbeef** [comment] 2021-05-23 04:12
@henryaj Thanks! I'll take a look.

(To be clear, Brakeman's parsing is provided by https://github.com/seattlerb/ruby_parser but I'll still see if I can fix it.)

**Comment by presidentbeef** [comment] 2021-05-23 04:30
This seems like a pretty specific failure - as a keyword argument value.

In the meantime, you could work around this with:

```ruby
updated_at: (..15).minutes.ago
```

**Comment by henryaj** [comment] 2021-05-25 09:48
Gotcha - thanks for the workaround! :)

**Comment by bibendi** [comment] 2021-06-10 12:05
I've got the same error with brakeman 5.0.4

```ruby
  def no_few_empty_events?
      user
        .created_events
        .merge(Event.kept.allowed.published.live)
        .where(rsvp_count: ..1)
        .count < MAX_EMPTY_EVENTS
    end
```

```
Error: app/policies/meet_by/event_policy.rb:63 :: parse error on value ".." (tDOT2) Could not parse app/policies/meet_by/event_policy.rb
Location: /usr/local/bundle/gems/racc-1.5.2/lib/racc/parser.rb:538:in `on_error'
```

The workaround with `.where(rsvp_count: (..1))` helps me. But I want to have more clear code :)

**Comment by DAmatheson** [comment] 2021-11-08 20:30
I'm having the same issue with a beginless range `..123` on `5.1.1`. Endless range is fine `123..` in the same scenario. 

The parenthesis workaround does work. 

`SomeModel.where(id: ..123)` is the scenario.

**Comment by presidentbeef** [comment] 2021-11-09 23:39
@DAmatheson and @zalom - try Brakeman 5.1.2 instead.

**Comment by zalom** [comment] 2021-11-10 06:25
@presidentbeef it works now. Thanks!
